const listings = [
    {
      title: "Cozy Cottage in the Woods",
      description: "A charming retreat surrounded by serene nature.",
      image: "https://unsplash.com/photos/nature-cottage",
      price: 120,
      location: "Asheville",
      country: "USA",
    },
    {
      title: "Modern Apartment with City View",
      description: "Spacious apartment with stunning city skyline views.",
      image: "https://unsplash.com/photos/city-apartment",
      price: 200,
      location: "New York",
      country: "USA",
    },
    {
      title: "Beachfront Villa",
      description: "Relax and unwind in this luxurious beachfront villa.",
      image: "https://unsplash.com/photos/beach-villa",
      price: 350,
      location: "Malibu",
      country: "USA",
    },
    {
      title: "Mountain Cabin Escape",
      description: "Rustic cabin with breathtaking mountain views.",
      image: "https://unsplash.com/photos/mountain-cabin",
      price: 150,
      location: "Denver",
      country: "USA",
    },
    {
      title: "Luxury Downtown Loft",
      description: "Stylish loft in the heart of downtown.",
      image: "https://unsplash.com/photos/downtown-loft",
      price: 250,
      location: "Los Angeles",
      country: "USA",
    },
    {
      title: "Charming Countryside Cottage",
      description: "Perfect for a peaceful getaway.",
      image: "https://unsplash.com/photos/countryside-cottage",
      price: 100,
      location: "Oxford",
      country: "UK",
    },
    {
      title: "Secluded Lakehouse",
      description: "Private lakehouse with stunning views.",
      image: "https://unsplash.com/photos/lakehouse",
      price: 300,
      location: "Lake Tahoe",
      country: "USA",
    },
    {
      title: "Romantic Paris Apartment",
      description: "Cozy and elegant apartment in Paris.",
      image: "https://unsplash.com/photos/paris-apartment",
      price: 220,
      location: "Paris",
      country: "France",
    },
    {
      title: "Chic Studio in Tokyo",
      description: "Modern and compact studio in the heart of Tokyo.",
      image: "https://unsplash.com/photos/tokyo-studio",
      price: 180,
      location: "Tokyo",
      country: "Japan",
    },
    {
      title: "Private Island Retreat",
      description: "Exclusive island experience with luxury amenities.",
      image: "https://unsplash.com/photos/private-island",
      price: 1000,
      location: "Bahamas",
      country: "Bahamas",
    },
    {
      title: "Eco-Friendly Treehouse",
      description: "Unique eco-friendly treehouse experience.",
      image: "https://unsplash.com/photos/treehouse",
      price: 130,
      location: "Portland",
      country: "USA",
    },
    {
      title: "Scenic Scottish Highlands Lodge",
      description: "Charming lodge with panoramic views.",
      image: "https://unsplash.com/photos/scottish-lodge",
      price: 170,
      location: "Highlands",
      country: "Scotland",
    },
    {
      title: "Desert Glamping Site",
      description: "Luxurious camping experience in the desert.",
      image: "https://unsplash.com/photos/desert-glamping",
      price: 200,
      location: "Joshua Tree",
      country: "USA",
    },
    {
      title: "Historic Castle Stay",
      description: "Live like royalty in this authentic castle.",
      image: "https://unsplash.com/photos/castle",
      price: 500,
      location: "Edinburgh",
      country: "Scotland",
    },
    {
      title: "Modern Family Home",
      description: "Perfect for families with spacious living areas.",
      image: "https://unsplash.com/photos/family-home",
      price: 300,
      location: "San Diego",
      country: "USA",
    },
    {
      title: "Tropical Bungalow",
      description: "Relax in paradise with this tropical retreat.",
      image: "https://unsplash.com/photos/tropical-bungalow",
      price: 220,
      location: "Bali",
      country: "Indonesia",
    },
    {
      title: "Urban Penthouse",
      description: "Luxurious penthouse with amazing city views.",
      image: "https://unsplash.com/photos/penthouse",
      price: 400,
      location: "Chicago",
      country: "USA",
    },
    {
      title: "Vintage Camper Van",
      description: "Explore on wheels with this unique camper.",
      image: "https://unsplash.com/photos/camper-van",
      price: 90,
      location: "Seattle",
      country: "USA",
    },
    {
      title: "Idyllic Village Home",
      description: "Charming home in a peaceful village setting.",
      image: "https://unsplash.com/photos/village-home",
      price: 140,
      location: "Cotswolds",
      country: "UK",
    },
    {
      title: "Snowy Mountain Chalet",
      description: "Cozy and warm chalet in a snowy paradise.",
      image: "https://unsplash.com/photos/snowy-chalet",
      price: 250,
      location: "Aspen",
      country: "USA",
    },
    {
      title: "Ocean View Penthouse",
      description: "Luxury living with breathtaking ocean views.",
      image: "https://unsplash.com/photos/ocean-penthouse",
      price: 450,
      location: "Sydney",
      country: "Australia",
    },
    {
      title: "Rustic Barn Conversion",
      description: "Unique stay in a renovated barn.",
      image: "https://unsplash.com/photos/barn",
      price: 180,
      location: "Somerset",
      country: "UK",
    },
    {
      title: "Mediterranean Villa",
      description: "Experience luxury with Mediterranean vibes.",
      image: "https://unsplash.com/photos/med-villa",
      price: 330,
      location: "Santorini",
      country: "Greece",
    },
    {
      title: "Safari Tent Experience",
      description: "Get close to nature with this unique safari stay.",
      image: "https://unsplash.com/photos/safari-tent",
      price: 270,
      location: "Serengeti",
      country: "Tanzania",
    },
    {
      title: "Traditional Ryokan",
      description: "Experience Japanese hospitality in a traditional ryokan.",
      image: "https://unsplash.com/photos/ryokan",
      price: 210,
      location: "Kyoto",
      country: "Japan",
    },
    {
      title: "Bohemian Loft",
      description: "Stylish loft with eclectic decor.",
      image: "https://unsplash.com/photos/bohemian-loft",
      price: 170,
      location: "Austin",
      country: "USA",
    },
    {
      title: "Minimalist Zen House",
      description: "Find peace in this minimalist retreat.",
      image: "https://unsplash.com/photos/zen-house",
      price: 230,
      location: "Seattle",
      country: "USA",
    },
    {
      title: "Riverside Cabin",
      description: "Charming cabin by the riverside.",
      image: "https://unsplash.com/photos/riverside-cabin",
      price: 190,
      location: "Nashville",
      country: "USA",
    },
    {
      title: "Luxury Yacht Stay",
      description: "Unforgettable stay on a luxury yacht.",
      image: "https://unsplash.com/photos/yacht",
      price: 700,
      location: "Monaco",
      country: "Monaco",
    },
  ];
  
  module.exports = {data: listings};